### ISSUE TITLE
Graphiql  React.render don`t work with 15.0.0 version

### ISSUE THREAD

**Issue by BoryaMogila** [chentsulin/koa-graphql#42]
In console React.render is not a function

**Comment by chentsulin** [comment]
Fixed via #40 and released as `v0.5.1`.
